### ISSUE TITLE
"Poll" mode for inmate scraper

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#10]
The current scraper process assumes a long, full-blown search of all inmates at once-a-day intervals. But because of the possibility of short-term prison stays, we need some faster, less bandwidth intensive ways of scraping.

I suspect a mix of two techniques could help: 

1) Polling regularly for new inmates using the last known jail id #. Right now, that's http://www2.cookcountysheriff.org/search2/details.asp?jailnumber=2012-1128234 -- if you polled every X minutes for 2012-1128235, you could quickly pick up new inmates at they're added. 
2) Searching the last X days' worth of inmates every hour or two to look for recent dropouts. The value of X should be whatever duration we think hour-level precision for time of discharge matters. For long stays, precise discharge time becomes less important, and so can be excluded.

I'm curious if these should be their own management commands or should be specified by a flag to scrape_inmates.

**Comment by fgregg** [comment]
I'm not sure if we need a temporal resolution of less than a day. The key thing is to gather information of people who bail out within a few hours.

**Comment by eads** [comment]
+1. A resolution on the order of a day seems right for this: I don't think we can rely on the a record appearing and disappearing to accurately reflect the length of stay on the order of minutes or even hours. 

Depending on our polling strategy, we may want to poll today and yesterday's inmates, though, to capture the inmate that is booked at 10pm and gets out at 2am.

**Comment by jimglover** [comment]
To be efficient we should poll often.  Polling for new inmates every few minutes by jail id is the most accurate way to stay efficient.  We want our information to be up-to-the-minute and up-to-date as possible.   We'll have a clearer picture of what's going on because as soon as something happens, we'll be notified.

**Comment by wilbertom** [comment]
Hey guys, some things we should consider as issues. First doing research on how often cook county updates their database. Currently the poll_mode will search while (booking_date < today) and not (booking_date <= today) because the database seems to be behind by a day. And lastly we should consider separating the process_urls into two parts, one function for iterating through the urls and another for saving each record's fields. It would save about 80 lines of code in the poll_mode.
