### ISSUE TITLE
Various graphs are too wide for browser width

### ISSUE THREAD

**Issue by andymboyle** [sc3/cookcountyjail#121]
Booking Per Day and Jail Population have graphs that go wider than my screen width, so need to figure out how to responsivize these.

**Comment by bepetersn** [comment]
Hey Andy,

Thanks for contributing. Technically, I think this and the other two issues you added should be associated with the sc3/26andcalifornia project, since they are all about its UI. This project only provides an API to the data we've collected from the CookCountyJail. 26th uses that API and data, but it displays it its own way.

**Comment by wilbertom** [comment]
Yup, [moving this issue](https://github.com/sc3/26thandcalifornia/issues/56) over to 26thandcalifornia.
