### ISSUE TITLE
ChargesHistory data is incorrect

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#144]
At record 39452, the charges and charges_citation fields data is swapped. This also means that the code that updates these fields is incorrect and needs to be fixed. 

The records from 1 up to and including 39451 are correct.

**Comment by wilbertom** [comment]
I just did a commit to try and fix this.

Someone should look over the data migration because I didn't have a big enough copy of the database to assert I didn't make any mistakes.

The scraper was also updated.

# Note

The migration has to be ran before the next scrape after the code is updated. Otherwise it will switch around the new correct values.

**Comment by nwinklareth** [comment]
I updated the website ad ran the migration and the data looks good. Thanks Wilberto.
