### ISSUE TITLE
Add all fields to model

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#2]
Add all fields from a page like http://www2.cookcountysheriff.org/search2/details.asp?jailnumber=2012-1121092 to the `InmateRecord` model.

**Comment by fgregg** [comment]
Awesome!

Couple of thoughts. 

First, we may want to coarsen up some data we are storing.

Instead of storing the DOB, let's store the inmate's age at the booking date. 

Also, I don't see a use case right now for keeping weight and height. If we want to store them anyway, let's round them to nearest three inches and ten pounds respectively.

This helps maintain the anonymity of the data.

Second, some of the fields might change: next court date, housing location, bail status, bail amount, charges.  Some of these WILL change, some of these I could imagine changing, but I'm not sure they will. How do want to handle these dynamics?
