### ISSUE TITLE
Running the Database Audit program should be added to daily scraper job

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#314]
After website scraping has run, the database should be audited and if there is a problem a notification should be sent out.

**Comment by bepetersn** [comment]
Norbert has pointed out the possibility of using Amazon's SES platform for sending out notification emails from our server: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/Welcome.html

**Comment by bepetersn** [comment]
I'm also considering Amazon's Simple Notification Service. It seems like it could fit our use case better:

http://docs.aws.amazon.com/sns/latest/dg/welcome.html

**Comment by bepetersn** [comment]
I managed to be able to send myself an email from the server through Amazon, using `sendmail` on the server. However, it was rather annoying to configure Linux and this particular mail client. The only thing that really made it possible was that there are  [instructions in Amazon's docs](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/sendmail.html) on how to configure `sendmail`, specifically. 

I have done more research, and I also would like to try to use AWS's [`boto`](https://github.com/boto) library for python. This would make configuring the SMTP client easier, for me, at least.

Even doing this still is kind of annoying, because I'm actually using my own email to send these notifications. I'd rather have a separate email address set up on server. Using [Postfix](https://help.ubuntu.com/community/PostfixBasicSetupHowto) to set up a simple email server on our machine might be able to make this happen, which might be able to use the Amazon `boto` API. Then maybe I'd have to [integrate postfix with Amazon](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/postfix.html)? I think?

There's so many things I don't know.

**Comment by bepetersn** [comment]
Moving my commentary on sending notifications to issue #319.

**Comment by bepetersn** [comment]
First version of this done.
