### ISSUE TITLE
Database audit notification fails when invoked in a certain way

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#327]
The error message is: python: can't open file 'scripts/notify.py': [Errno 2] No such file or directory

This is a path problem. The script is not running in /home/ubuntu/apps/cookcountyjail, which is the assumption made in the script. Check line 14 for an example of how to solve this defect.

**Comment by nwinklareth** [comment]
Brian, this has not been fixed. Please leave it open.

**Comment by nwinklareth** [comment]
The first symptom was the that the file could not be found, once found it did not run so notification is not occurring. We could close this one and open another one, don't see the point in that.

**Comment by bepetersn** [comment]
I honestly don't know what the problem with this is, so for the purpose of better understanding, we can leave it open. At the moment, I have just commented out the notifiying section of the scraper.sh. 

I opened another issue, #330, because it seemed like we weren't interested in solving this problem this way anymore. Did I misinterpret you in that regard?

**Comment by nwinklareth** [comment]
No when I wrote my message I did not know about #330. So I am closing this one and we will use #330 to get audit notifications to work.

The original symptom identified in this issue has been resolved. In doing so it uncovered another problem which is being addressed by issue #330.
