### ISSUE TITLE
v1 API no longer responded to requests

### ISSUE THREAD

**Issue by nwinklareth** [sc3/cookcountyjail#359]
On 2014/05/04 it was discovered that trying to access the v1 API with the following URLs did not work:
- http://cookcountyjail.recoveredfactory.net
- http://cookcountyjail.recoveredfactory.net/api/1.0/countyinmate/?format=json

**Comment by bepetersn** [comment]
Still not working? It does for me, anyway.

**Comment by wilbertom** [comment]
We should look at the server logs to see how long it was out.

**Comment by nwinklareth** [comment]
The logs won't tell us. I created this issue to track that we had this
problem, which Brian had fixed and he thought that the problem still
existed which it did not.

On Wed, May 7, 2014 at 8:34 AM, Wilberto Morales
notifications@github.comwrote:

> We should look at the server logs to see how long it was out.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sc3/cookcountyjail/issues/359#issuecomment-42427027
> .

## 

Regards

## Norbert

Norbert Winklareth

**Comment by bepetersn** [comment]
Ah, sorry for forgetting.

---

The issue came up during my changing the locations of some important django files, in particular `wsgi.py`. The problem arose after these changes were pushed to the server, using our fabric `production master deploy` command. At the end of this command, the production gunicorn server is restarted. 

In essence, the `gunicorn.sh` file failed to locate `wsgi.py`, which is actually what runs the django app. But unlike you might expect, the gunicorn service still ran, and not only that, it said nothing about its failure to find a wsgi application. It still logged all the requests made to it (but not their results), and simply didn't pass any of them along to the django application.  

Anyway, I figured out what was happening after staring at the live gunicorn process on the server for awhile -- in the `gunicorn.sh` file, we used to pass in a module level reference, `cookcountyjail.wsgi:application`, by argument. Changing this to `countyapi.wsgi:application` solved the issue.
