### ISSUE TITLE
Create south data migration for new housing location model

### ISSUE THREAD

**Issue by eads** [sc3/cookcountyjail#52]

**Comment by wilbertom** [comment]
### Working on This

Hey team, I started working on this but I got stuck because I'm not sure how we want to handle this as a team. When creating the data migration do we want to?
- Create a new field on the CountyInmate table and do some "stuff" on the housing_location field and migrate it to the new field. 
- Or create a HousingHistory and HousingLocation record from the housing_location field and then drop the housing_location field.
